version: 2  # Specify the version for Read the Docs configuration
build:
  os: ubuntu-22.04  # Specify Ubuntu version
  tools:
    python: "3.8"  # Specify Python version

sphinx:
  configuration: docs/source/conf.py  # Specify the location of your Sphinx config file

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
