site_name: Document Q&A System
site_description: A multi-model document question-answering system
theme:
  name: material

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage Guide: usage.md
  - API Reference: api-reference.md
  - Configuration: configuration.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition

# Corrected build section with supported Ubuntu OS version
build:
  os: ubuntu-22.04  # Choose one of the supported Ubuntu versions
  tools:
    python: "3.8"  # Specify Python version
