site_name: Document Q&A System
site_description: A multi-model document question-answering system
theme:
  name: material

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage Guide: usage.md
  - API Reference: api-reference.md
  - Configuration: configuration.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
